name: Default
on:
  push:
    branches:
      - main
jobs:
  verify-code-format-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
      - name: Install Dependencies
        run: npm install
      - name: Check code format
        run: npm run format:check
      - name: Check build
        run: npm run build
      - name: Check tests
        run: npm run jest:test
